### ISSUE TITLE
Build is error of 2.7

### ISSUE THREAD

**Issue by HanSuJe** [Shimada666/vue-demi-sfc-component-template#2]
### hello  ,  when i building version of 2.7,  that is error,  details:
failed to load config from E:\EPCdemo\vue-demi-sfc-component-template\vue2.7-playground\vite.config.ts
error during build:
TypeError: Cannot read properties of undefined (reading 'warn')
    at Object.<anonymous> (E:\EPCdemo\vue-demi-sfc-component-template\node_modules\.pnpm\vue-demi@0.13.11_@vue+composition-api@1.7.1_vue@3.2.45\node_modules\vue-demi\lib\index.cjs:11:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\EPCdemo\vue-demi-sfc-component-template\vue2.7-playground\vite.config.ts:40:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .ts] (E:\EPCdemo\vue-demi-sfc-component-template\node_modules\.pnpm\vite@2.9.15_sass@1.57.1\node_modules\vite\dist\node\chunks\dep-689425f3.js:62006:20)

**Comment by HanSuJe** [comment]
ok ,  i  resolve the problem, because it not find suitable path in building v2.7,  i create one function to get buiding object, that's ok

**Comment by Shimada666** [comment]
Is it because the resolve function is not used?
